# fly.toml app configuration file generated for klipper on 2023-06-24T15:42:12+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "klipper"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
